### ISSUE TITLE
Way of using own samples?

### ISSUE THREAD

**Issue by jeremyworger** [hmartelb/NSynth-MIDI-Renderer#3]
Hi there, is there a method where instead of using the nsynth samples, one could use a corpus of their own sounds? For instance any set of synthesizer samples?

**Comment by hmartelb** [comment]
In order to do that, you need to change how the note names are obtained. Just modify this function to suit your needs:

https://github.com/hmartelb/NSynth-MIDI-Renderer/blob/a70742ee999d034db2b84a824b96c73b3d78b648/NoteSynthesizer.py#L22-L24

If you work on some commonly used synthesizer samples that can be useful for others, feel free to submit a PR with the changes. Cheers!

**Comment by jeremydeanw** [comment]
Is there an easy way to obtain all the annotation from any synthesizer samples though?
I don't have much python experience, I was hoping to use these samples:
https://rolls.bublup.com/view/872a3ffd-ed50-4875-8681-8a2729f5cbc5
For instance the Fairlight or the Mirage (they are all wav samples, organized by type)

**Comment by jeremyworger** [comment]
Im not much of a python user.....I'm assuming I need to train nsynth on my own wav files first, do you know if there is a straight forward way of doing so?

**Comment by hmartelb** [comment]
I don't understand what your end goal is. 

The code in this repository is only intended to generate audio from MIDI files using the existing audio samples in the NSynth dataset (thus, no need to train any model). It just takes the corresponding notes of the selected instrument and places them to match the arrangement of the MIDI file. As a result you get an audio render containing the MIDI file played with the selected instrument.

You can use any samples you want as long as they are annotated in a regular format that can be retrieved with the function I mentioned. I hope it helps

**Comment by jeremydeanw** [comment]
Hi thanks. How can I annotate samples without velocity info or source type?  I have folders with wav files of different types of instruments....I'm not sure how to edit lines 22-24 to accommodate only the instrument type.

**Comment by jeremydeanw** [comment]
Also, in this case, how can multiple instruments be used?  
It seems to work if I rename any wav file a name of a wav file in the nsynth dataset, so im assuming it's just a naming problem, and changing the default so that it can be multiple instruments/any sounds within a folder. Unfortunately im terrible a python so I don't know what im doing. Would love to see it as a feature.  Cheers.
